**Import Library**

In [ ]:
import pandas as pd
import numpy as np
import os

# Display all columns
pd.set_option('display.max_columns', None)

**Load Dataset**

In [ ]:
tables = pd.read_html(
    "/content/Data_Penduduk Pendatang ke Provinsi DKI Jakarta - tabel.xls"
)

print(f"Jumlah tabel: {len(tables)}")
df = tables[0]

Jumlah tabel: 1

**Preview Data**

In [ ]:
df.head()

,periode_data,wilayah,kecamatan,kelurahan,provinsi_asal,wilayah_asal,jumlah
0,2025,KOTA ADM. JAKARTA PUSAT,GAMBIR,CIDENG,JAWA BARAT,BANDUNG,4
1,2025,KOTA ADM. JAKARTA PUSAT,GAMBIR,CIDENG,JAWA BARAT,BOGOR,8
2,2025,KOTA ADM. JAKARTA PUSAT,GAMBIR,CIDENG,JAWA BARAT,CIAMIS,1
3,2025,KOTA ADM. JAKARTA PUSAT,GAMBIR,CIDENG,JAWA BARAT,KARAWANG,1
4,2025,KOTA ADM. JAKARTA PUSAT,GAMBIR,CIDENG,JAWA BARAT,KOTA BANDUNG,3

In [ ]:
df.tail()

,periode_data,wilayah,kecamatan,kelurahan,provinsi_asal,wilayah_asal,jumlah
28172,2025,KOTA ADM. JAKARTA SELATAN,PANCORAN,RAWAJATI,SUMATERA BARAT,AGAM,3
28173,2025,KOTA ADM. JAKARTA SELATAN,PANCORAN,RAWAJATI,SUMATERA BARAT,KOTA PADANG,4
28174,2025,KOTA ADM. JAKARTA SELATAN,PANCORAN,RAWAJATI,SUMATERA BARAT,KOTA PADANG PANJANG,1
28175,2025,KOTA ADM. JAKARTA SELATAN,PANCORAN,RAWAJATI,SUMATERA BARAT,KOTA PARIAMAN,1
28176,2025,KOTA ADM. JAKARTA SELATAN,PANCORAN,RAWAJATI,SUMATERA BARAT,KOTA PAYAKUMBUH,2

In [ ]:
df.sample(5)

,periode_data,wilayah,kecamatan,kelurahan,provinsi_asal,wilayah_asal,jumlah
23646,2025,KOTA ADM. JAKARTA TIMUR,DUREN SAWIT,PONDOK BAMBU,JAWA TENGAH,BREBES,25
5483,2025,KOTA ADM. JAKARTA UTARA,KOJA,RAWA BADAK SELATAN,SUMATERA UTARA,KOTA MEDAN,7
23573,2025,KOTA ADM. JAKARTA TIMUR,CIPAYUNG,CILANGKAP,KALIMANTAN TENGAH,KOTA PALANGKARAYA,1
18986,2025,KOTA ADM. JAKARTA SELATAN,JAGAKARSA,LENTENG AGUNG,JAWA TENGAH,BOYOLALI,2
19222,2025,KOTA ADM. JAKARTA TIMUR,KRAMATJATI,BATU AMPAR,KALIMANTAN TIMUR,KOTA BALIKPAPAN,2

**Dataset Information**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28177 entries, 0 to 28176
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   periode_data   28177 non-null  int64
 1   wilayah        28177 non-null  object
 2   kecamatan      28177 non-null  object
 3   kelurahan      28177 non-null  object
 4   provinsi_asal  28177 non-null  object
 5   wilayah_asal   28177 non-null  object
 6   jumlah         28177 non-null  int64
dtypes: int64(2), object(5)
memory usage: 1.5+ MB

**Dataset Shape**

In [ ]:
print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Rows    : 28177
Columns : 7

**Check Data Types**

In [ ]:
df.dtypes

periode_data      int64
wilayah          object
kecamatan        object
kelurahan        object
provinsi_asal    object
wilayah_asal     object
jumlah            int64
dtype: object

**Check Missing Values**

In [ ]:
df.isnull().sum()

periode_data     0
wilayah          0
kecamatan        0
kelurahan        0
provinsi_asal    0
wilayah_asal     0
jumlah           0
dtype: int64

In [ ]:
missing = (
    df.isnull().sum()
      .to_frame("Missing")
)

missing["Percentage"] = (
    missing["Missing"] / len(df) * 100
)

missing.sort_values("Percentage", ascending=False)

               Missing  Percentage
periode_data         0         0.0
wilayah              0         0.0
kecamatan            0         0.0
kelurahan            0         0.0
provinsi_asal        0         0.0
wilayah_asal         0         0.0
jumlah               0         0.0

**Check Duplicate Rows**

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df = df.drop_duplicates()

**Check Unique Values**

In [ ]:
for col in df.columns:
    print("="*50)
    print(col)
    print(df[col].nunique())

==================================================
periode_data
1
==================================================
wilayah
6
==================================================
kecamatan
44
==================================================
kelurahan
267
==================================================
provinsi_asal
38
==================================================
wilayah_asal
508
==================================================
jumlah
109

**Statistical Summary**

In [ ]:
df.describe()

       periode_data        jumlah
count       28177.0  28177.000000
mean         2025.0      3.915498
std             0.0      7.355773
min          2025.0      1.000000
25%          2025.0      1.000000
50%          2025.0      2.000000
75%          2025.0      4.000000
max          2025.0    260.000000

In [ ]:
df.describe(include="all")

,periode_data,wilayah,kecamatan,kelurahan,provinsi_asal,wilayah_asal,jumlah
count,28177.0,28177,28177,28177,28177,28177,28177.000000
unique,NaN,6,44,267,38,508,NaN
top,NaN,KOTA ADM. JAKARTA TIMUR,CENGKARENG,KAPUK,JAWA BARAT,BOGOR,NaN
freq,NaN,7904,1104,226,5014,263,NaN
mean,2025.0,NaN,NaN,NaN,NaN,NaN,3.915498
std,0.0,NaN,NaN,NaN,NaN,NaN,7.355773
min,2025.0,NaN,NaN,NaN,NaN,NaN,1.000000
25%,2025.0,NaN,NaN,NaN,NaN,NaN,1.000000
50%,2025.0,NaN,NaN,NaN,NaN,NaN,2.000000
75%,2025.0,NaN,NaN,NaN,NaN,NaN,4.000000
max,2025.0,NaN,NaN,NaN,NaN,NaN,260.000000

**Check Invalid Values**

In [ ]:
df[df["jumlah"] < 0]

Empty DataFrame
Columns: [periode_data, wilayah, kecamatan, kelurahan, provinsi_asal, wilayah_asal, jumlah]
Index: []

**Check Whitespace**

In [ ]:
text_cols = df.select_dtypes(include="object").columns

for col in text_cols:
    df[col] = df[col].str.strip()

**Standardize Text**

In [ ]:
for col in text_cols:
    df[col] = df[col].str.title()

**Rename Columns**

In [ ]:
df.columns = [
    "year",
    "destination_city",
    "destination_district",
    "destination_village",
    "origin_province",
    "origin_city",
    "total_migrants"
]

**Final Check**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28177 entries, 0 to 28176
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   year                  28177 non-null  int64
 1   destination_city      28177 non-null  object
 2   destination_district  28177 non-null  object
 3   destination_village   28177 non-null  object
 4   origin_province       28177 non-null  object
 5   origin_city           28177 non-null  object
 6   total_migrants        28177 non-null  int64
dtypes: int64(2), object(5)
memory usage: 1.5+ MB

In [ ]:
df.head()

,year,destination_city,destination_district,destination_village,origin_province,origin_city,total_migrants
0,2025,Kota Adm. Jakarta Pusat,Gambir,Cideng,Jawa Barat,Bandung,4
1,2025,Kota Adm. Jakarta Pusat,Gambir,Cideng,Jawa Barat,Bogor,8
2,2025,Kota Adm. Jakarta Pusat,Gambir,Cideng,Jawa Barat,Ciamis,1
3,2025,Kota Adm. Jakarta Pusat,Gambir,Cideng,Jawa Barat,Karawang,1
4,2025,Kota Adm. Jakarta Pusat,Gambir,Cideng,Jawa Barat,Kota Bandung,3

**Export Clean Dataset**

In [ ]:
df.to_csv(
    "/content/pendatang_clean.csv",
    index=False
)